# Generated by Django 5.2.3 on 2025-06-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cct', models.TextField(blank=True, null=True)),
                ('clave_adscripcion', models.TextField(blank=True, null=True)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('nombre_departamento_corto', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('calle_numero', models.TextField(blank=True, null=True)),
                ('colonia_zona', models.TextField(blank=True, null=True)),
                ('codigo_postal', models.TextField(blank=True, null=True)),
                ('ciudad_estado', models.TextField(blank=True, null=True)),
                ('telefono_plantel', models.TextField(blank=True, null=True)),
                ('telefono_plantel2', models.TextField(blank=True, null=True)),
                ('extension_depto', models.TextField(blank=True, null=True)),
                ('extensiones_aux', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('coordinador_administrativo', models.TextField(blank=True, null=True)),
                ('coordinador_academico', models.TextField(blank=True, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('zona', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'adscripcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Adscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave_adscripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('zona', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.CharField(default='1', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adscripcion',
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('no', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('adscripcion', models.TextField(blank=True, null=True)),
                ('departamento', models.TextField(blank=True, null=True)),
                ('clave', models.TextField(blank=True, null=True)),
                ('rfc', models.TextField(blank=True, null=True)),
                ('curp', models.TextField(blank=True, null=True)),
                ('puesto', models.TextField(blank=True, null=True)),
                ('sindicato', models.TextField(blank=True, null=True)),
                ('fecha_de_ingreso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planilla',
            },
        ),
        migrations.CreateModel(
            name='Plazas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('denominacion', models.CharField(max_length=255)),
                ('zona_economica', models.CharField(max_length=10)),
                ('nivel_salarial', models.CharField(max_length=10)),
                ('plazas', models.IntegerField()),
                ('horas', models.IntegerField()),
            ],
            options={
                'db_table': 'plazas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasena', models.CharField(max_length=128)),
                ('ultimo_ingreso', models.DateTimeField(blank=True, null=True)),
                ('autorizacion', models.CharField(max_length=20)),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('estatus', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
