# Generated by Django 5.2.3 on 2025-06-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave_adscripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('zona', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'planilla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True, null=True)),
                ('adscripcion', models.TextField(blank=True, null=True)),
                ('departamento', models.TextField(blank=True, null=True)),
                ('clave', models.BigIntegerField(blank=True, null=True)),
                ('rfc', models.TextField(blank=True, null=True)),
                ('curp', models.TextField(blank=True, null=True)),
                ('puesto', models.TextField(blank=True, null=True)),
                ('fecha_de_ingreso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
