# Generated by Django 5.2.3 on 2025-06-23 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0002_plazas_alter_adscripcion_options_alter_planilla_no_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adscripcion',
            table='adscripcion',
        ),
        migrations.AlterModelTable(
            name='plazas',
            table='plazas',
        ),
    ]
