# Generated by Django 5.2.3 on 2025-06-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0003_alter_adscripcion_table_alter_plazas_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilla',
            name='sindicato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planilla',
            name='clave',
            field=models.TextField(blank=True, null=True),
        ),
    ]
