# Generated by Django 5.2.1 on 2025-06-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0004_planilla_sindicato_alter_planilla_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adscripcion',
            name='activo',
        ),
    ]
