# Generated by Django 5.2.1 on 2025-06-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0005_remove_adscripcion_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adscripcion',
            name='activo',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterModelTable(
            name='planilla',
            table=None,
        ),
    ]
