# Generated by Django 5.2.1 on 2025-06-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla', '0006_adscripcion_activo_alter_planilla_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='planilla',
            table='planilla',
        ),
    ]
